---
- hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install Dependencies
      apt: name={{ item }} state=latest force_apt_get=yes update_cache=yes
      loop: ['aptitude']

    # Install Apache
    - name: Install Apache2
      shell: sudo apt install apache2 -y

    # Set Timezone
    - name: Update Timezone to Africa/Lagos
      copy: content=Africa/Lagos dest=/etc/timezone owner=root group=root mode=0644
      register: timezone

    - name: Reconfigure Timezone Data (if changed)
      shell: dpkg-reconfigure -f noninteractive tzdata
      when: timezone.changed

    # Permission
    - name: Permission
      shell: sudo chmod 777 -R /var/www/html/

    # Simple HTML Page
    - name: Simple Server HTML Page
      shell: echo "<h1 style="font-size: 46px"><strong>My Server is $(hostname -f)<strong></h1>" > /var/www/html/index.html

    # Restart Apache
    - name: Restart Apache
      shell: sudo systemctl restart apache2




      